/**
 * The public surface of the game simulation.
 *
 * `ui/` imports from here. Nothing in `core/` imports from `ui/`, Angular, Capacitor, or
 * any DOM API — the whole module graph runs headless in Node, which is what makes balance
 * testable by simulating thousands of hours instead of playing them.
 *
 * **Snapshotting for the UI:** every core function returns a new state and never mutates
 * its argument, so the UI can hold a returned state directly as its snapshot. Do not run it
 * through `structuredClone` — `Numeric` values are `Decimal` instances, and
 * `structuredClone` strips the prototype, leaving a plain `{ mantissa, exponent }` object
 * whose `.add()` throws at the next tick. The copy is unnecessary given purity and actively
 * breaks the numbers.
 */
export {
  ATB_THRESHOLD,
  BATTLE_TICK_MS,
  MAX_BATTLE_TICKS,
  PRESSURE_AFTER_TICKS,
  PRESSURE_PER_TICK,
  pressureAt,
  ticksToMs,
  ticksUntilReady,
} from './battle/clock';
export {
  applyRowBonus,
  MAX_ACCURACY,
  MAX_PENETRATION,
  MAX_RESIST,
  matchupKey,
  ticksPerAction,
  toAmount,
  toCombatant,
  toCombatRules,
  toCombatStats,
  toCurrencyAmounts,
  toRates,
  toSkill,
} from './battle/content';
export { clampEnergy, isCharged, MAX_ENERGY, toEnergyRules } from './battle/energy';
export {
  applyLineupBonus,
  isNeutralLineup,
  lineupBonus,
  NO_LINEUP,
  NO_LINEUP_BONUS,
  toLineupRules,
} from './battle/lineup';
export {
  baseDamage,
  critChance,
  critMultiplier,
  effectiveDefence,
  factionMultiplier,
  hitChance,
  resistedShare,
  rollAttack,
  statusChance,
  type AttackRoll,
} from './battle/damage';
export { applyBattleResult, reconcileClearedStages, type DropAward } from './battle/progress';
export { emblemDropChance, rollEmblems, type EmblemDropData } from './emblems';
export {
  applySignatureAbility,
  clampSignatureLevel,
  levelSignature,
  maxSignatureLevel,
  mergeBonus,
  nextSignatureTierAt,
  signatureBonus,
  signatureCost,
  signatureTier,
  signatureTierIndex,
  signatureTotalCost,
  signatureUnlocked,
  type SignatureLookup,
  type SignatureResult,
} from './signature/signature';
export {
  NO_SIGNATURE_BONUS,
  type SignatureAbilityTierData,
  type SignatureBonus,
  type SignatureFailure,
  type SignatureItemData,
  type SignatureRulesData,
  type SkillOverrideData,
} from './signature/types';
export {
  battleSeed,
  simulateBattle,
  type CombatantOpening,
  type PartyOpening,
} from './battle/simulate';
export {
  applyDescentBonus,
  cardOffer,
  descentBonus,
  descentCard,
  descentCardId,
  descentCards,
  descentOffer,
  familyFloor,
  isNeutralDescentBonus,
  choiceProgress,
  rankWeight,
  type CardLadderRules,
} from './descent/cards';
export {
  applyDescentResult,
  canStartDescent,
  dailyDescentFactions,
  descentBoards,
  descentCardsOwed,
  descentChoices,
  descentFightAt,
  descentFights,
  descentFightSummons,
  descentLevel,
  descentLump,
  descentRunFor,
  descentStatus,
  isDescentUnlocked,
  nextDescentFight,
  parseDescent,
  resolveDescentFight,
  serializeDescent,
  startDescent,
  takeDescentCard,
  type DescentBattleOutcome,
  type DescentDropAward,
  type DescentStanding,
} from './descent/run';
export {
  DESCENT_STATS,
  NO_DESCENT_BONUS,
  type DescentBonus,
  type DescentCard,
  type DescentEncounterData,
  type DescentFamilyData,
  type DescentFight,
  type DescentLevelData,
  type DescentRankData,
  type DescentRulesData,
  type DescentRun,
  type DescentStat,
  type DescentStatus,
  type DescentSummonsData,
} from './descent/types';
export {
  adjacentCamps,
  cheapestStaminaTo,
  exitReachable,
  expeditionMapIssues,
  parseExpeditionGrid,
  reachableChests,
  reachableTiles,
  type ExpeditionGrid,
  type ExpeditionTile,
  type ExpeditionTileKind,
} from './expedition/map';
export {
  abandonExpedition,
  applyExpeditionResult,
  completeExpedition,
  expeditionCampSummons,
  expeditionCardsOwed,
  expeditionChestPayout,
  expeditionCleared,
  expeditionExitOpen,
  expeditionLevel,
  expeditionLump,
  expeditionMapOpen,
  expeditionRecordFor,
  expeditionRunFor,
  expeditionsCompleted,
  expeditionStageId,
  expeditionStaminaLeft,
  expeditionStaminaSpent,
  expeditionStatus,
  fightableExpeditionCamps,
  isExpeditionUnlocked,
  nextExpeditionCamp,
  parseExpedition,
  parseExpeditionRecords,
  resolveExpeditionCamp,
  serializeExpedition,
  serializeExpeditionRecords,
  startExpedition,
  takeExpeditionCard,
  type ExpeditionBattleOutcome,
  type ExpeditionDropAward,
} from './expedition/run';
export {
  EMPTY_EXPEDITION_RECORD,
  type ExpeditionCampData,
  type ExpeditionChestContents,
  type ExpeditionChestData,
  type ExpeditionMapData,
  type ExpeditionRecord,
  type ExpeditionRulesData,
  type ExpeditionRun,
  type ExpeditionStatus,
  type ExpeditionSummonsData,
} from './expedition/types';
export { chooseSkill, selectTargets, type FighterView } from './battle/skills';
export {
  absorbDamage,
  applyStatus,
  cleanseStatuses,
  effectiveStats,
  isStunned,
  nextExpiry,
  partitionExpired,
  shieldTotal,
  statModifier,
  toActiveStatus,
} from './battle/status';
export {
  ROWS,
  type ActiveStatus,
  type AuthoredAmount,
  type AuthoredCurrencies,
  type BattleEvent,
  type BattleOutcome,
  type BattleResult,
  type BattleReward,
  type Combatant,
  type CombatantData,
  type CombatantSnapshot,
  type CombatRules,
  type CombatRulesData,
  type CombatStats,
  type DamageType,
  type EnemyData,
  type EnemyFormationData,
  type FactionMatchupData,
  type FormationData,
  type LineupBonus,
  type LineupLadderStepData,
  type LineupRules,
  type LineupRulesData,
  type LineupSummary,
  type LineupTierData,
  type LineupTierMatch,
  type ModifiableStat,
  type Row,
  type RowBonusData,
  type Side,
  type Skill,
  type EnergyRules,
  type EnergyRulesData,
  type SkillConditionData,
  type SkillData,
  type SkillEffectData,
  type SkillTarget,
  type StageData,
  type StageEncounterData,
  type StageKind,
  type StatBlockData,
  type StatusData,
} from './battle/types';
export {
  advancePosition,
  chaptersCleared,
  chapterSize,
  clampPosition,
  ladderShape,
  positionAt,
  resolveLadder,
  resolveStage,
  stageIndex,
  stageKindAt,
  stagePayout,
  stagesInChapter,
  stagesThroughChapter,
  totalStages,
  type ChapterCurveData,
  type ChapterData,
  type ChaptersCleared,
  type LadderPosition,
  type LadderShape,
  type StagePayout,
  type StageRewardCurveData,
} from './ladder';
export {
  allProgress,
  claimAchievements,
  counterValue,
  emptyAchievements,
  parseAchievements,
  trackProgress,
  unclaimedReward,
  type AchievementCounter,
  type AchievementLedger,
  type AchievementProgress,
  type AchievementTrackData,
  type ClaimResult,
} from './achievements';
export {
  allBountyProgress,
  awayMembers,
  benchMembers,
  boardDayIndex,
  bountyPayout,
  bountyProgress,
  collectBounty,
  collectReadyBounties,
  dailyBoard,
  dispatchBounty,
  dispatchOf,
  dispatchOpenBounties,
  emptyDispatches,
  isPayoutEmpty,
  isUnlocked,
  meetsRequirement,
  msUntilRotation,
  parseDispatches,
  repairDispatches,
  runningBounties,
  serializeDispatches,
  type BountyBoardRulesData,
  type BountyData,
  type BountyFailure,
  type BountyProgress,
  type BountyRequirement,
  type BountyResult,
  type CollectAllResult,
  type Dispatch,
  type DispatchAllResult,
} from './bounties';
export {
  allQuestProgress,
  claimQuests,
  emptyQuestWindows,
  emptyWindow,
  periodIndex,
  QUEST_PERIODS,
  questProgress,
  parseQuestWindows,
  rollQuestWindows,
  windowEndsAt,
  type QuestClaimResult,
  type QuestCounter,
  type QuestData,
  type QuestPeriod,
  type QuestProgress,
  type QuestRulesData,
  type QuestWindow,
  type QuestWindows,
} from './quests';
export {
  accrue,
  canAfford,
  credit,
  CURRENCY_IDS,
  debit,
  emblemRatePerSecond,
  emptyWallet,
  isEmpty,
  parseRates,
  parseWallet,
  raiseRates,
  RATE_CURRENCY_IDS,
  serializeRates,
  serializeWallet,
  summonRatePerSecond,
  withEmblemRate,
  withSummonRate,
  zeroRates,
  type CurrencyAmounts,
  type CurrencyId,
  type EmblemRateCurve,
  type IdleRateCurves,
  type RateCurrencyId,
  type Rates,
  type SummonRateCurve,
  type Wallet,
} from './currency';
export {
  addGear,
  alloyStep,
  autoEquip,
  canEnhance,
  enhance,
  enhanceCost,
  enhanceToAffordable,
  equip,
  equippedBy,
  findGear,
  gearId,
  goldStep,
  investedAlloy,
  loadoutOf,
  repairLoadouts,
  salvage,
  salvageValue,
  unequip,
  unequippedGear,
  useAsMaterial,
  type AutoEquipResult,
  type GearFailure,
  type GearResult,
  type GearSpec,
} from './gear/inventory';
export {
  dropCount,
  gradeWeights,
  rollDrops,
  rollGear,
  unlockedGrades,
  weightedIndex,
  type Draw,
} from './gear/roll';
export {
  buyGear,
  gearShopOffers,
  gearShopSlot,
  msUntilRestock,
  offerPrice,
  type GearShopFailure,
  type GearShopResult,
} from './gear/shop';
export {
  applyGearBonus,
  clampGearLevel,
  clampGradeIndex,
  gearLookup,
  gearProfile,
  gearScale,
  gradeAt,
  isAligned,
  isNeutralBonus,
  itemBonus,
  loadoutBonus,
  maxGearLevel,
  maxLoadoutBonus,
  type GearLookup,
} from './gear/stats';
export {
  emptyGearShop,
  emptyLoadout,
  GEAR_ARCHETYPES,
  GEAR_SLOTS,
  GEAR_STATS,
  loadoutItems,
  NO_GEAR_BONUS,
  type GearAlignment,
  type GearArchetype,
  type GearBonus,
  type GearDropData,
  type GearEnhanceData,
  type GearGradeData,
  type GearItem,
  type GearLoadout,
  type GearOffer,
  type GearRulesData,
  type GearShopData,
  type GearShopState,
  type GearSlot,
  type GearStat,
  type GearStatProfile,
} from './gear/types';
export { CHARACTER_TIERS, growthAt, type CharacterTier, type GrowthData } from './growth';
export { ascendedChance, legendaryChance, pull } from './gacha/pull';
export {
  isEligible,
  offerTargets,
  purchase,
  type ShopFailure,
  type ShopOfferData,
  type ShopResult,
} from './gacha/shop';
export {
  type BannerData,
  type GachaRulesData,
  type PityCurveData,
  type PityRulesData,
  type PullFailure,
  type PullOutcome,
  type PullResult,
} from './gacha/types';
export {
  ascend,
  ascendAll,
  nextAscension,
  pathFor,
  type AscensionStep,
  type AscensionSummary,
  type FactionLookup,
} from './roster/ascend';
export {
  kitSlots,
  nextSkillUnlock,
  ordinaryUnlock,
  skillCeiling,
  unlockedSkills,
  type KitRulesData,
  type KitSlot,
} from './roster/kit';
export {
  canLevelUp,
  clampLevel,
  cumulativeLevelCost,
  levelCapFor,
  levelCost,
  maxAffordableLevel,
  type CostTermData,
  type LevelCurveData,
} from './roster/level';
export {
  ascensionCost,
  clampRarityIndex,
  copyCost,
  fullAscensionCost,
  growthFloor,
  rarityAt,
  rarityFamily,
  rarityIndex,
  rarityLabel,
  startRarityIndex,
} from './roster/rarity';
export {
  effectiveLevel,
  isResonated,
  maxAffordableResonance,
  resonanceAnchors,
  resonanceCeiling,
  resonanceFloor,
  resonancePlan,
  type ResonancePlan,
  type ResonanceRaise,
} from './roster/resonance';
export {
  benchMember,
  findOwned,
  grantCopies,
  grantStarters,
  levelUp,
  levelUpToAffordable,
  placeInRow,
  raiseResonance,
  raiseResonanceToAffordable,
  repairOwned,
  setFormation,
  withoutMember,
  type CharacterLookup,
  type RosterFailure,
  type RosterResult,
} from './roster/roster';
export {
  growthMultiplier,
  scaleStats,
  toBattleCombatant,
  toEnemyCombatant,
  type SignatureAward,
} from './roster/stats';
export {
  MAX_RARITY_INDEX,
  RARITIES,
  RARITY_FAMILIES,
  type AscensionLadder,
  type AscensionPath,
  type AscensionRules,
  CHARACTER_ROLES,
  type CharacterData,
  type CharacterRole,
  type FactionData,
  type OwnedCharacter,
  type RarityFamily,
  type RarityId,
} from './roster/types';
export {
  Decimal,
  isUsable,
  num,
  ONE,
  parseOr,
  serialize as serializeNumeric,
  tryParse,
  ZERO,
  type Numeric,
} from './numeric';
export {
  accrueDiscrete,
  EMPTY_OFFLINE_REPORT,
  MIN_PLAUSIBLE_TICK_MS,
  paidNothing,
  resume,
  type DiscreteAccrual,
  type OfflineReport,
} from './offline';
export { deriveSeed, derivedStream, resumeStream, type RngState, type RngStream } from './rng';
export { loadSave, loadSaveText, type LoadResult } from './save/load';
export {
  FutureSaveVersionError,
  migrate,
  MIGRATIONS,
  UnknownSaveVersionError,
  type Migration,
  type RawSave,
} from './save/migrate';
export { type AnySaveData, type CurrentSaveData, type SaveDataV0 } from './save/schema';
export {
  fromSaveData,
  toSaveData,
  type RepairIssue,
  type RepairOptions,
  type RepairResult,
} from './save/serialize';
export { SAVE_VERSION } from './save/version';
export {
  CAMPAIGN_ACTIVITY,
  crewFor,
  factionMeetsLock,
  lockOf,
  meetsLock,
  partyMeetsFactionLock,
  partyMeetsLock,
  type ActivityData,
  type ActivityKind,
  type FactionLock,
} from './activity';
export {
  allFormationMembers,
  BACK_ROW_SIZE,
  CAMPAIGN_FORMATION,
  emptyFormation,
  emptyFormationBook,
  formationIn,
  formationMembers,
  formationSize,
  FRONT_ROW_SIZE,
  newGame,
  PARTY_SIZE,
  rowCapacity,
  stampSaveTime,
  type FormationBook,
  type GameState,
  type NewGameOptions,
  type PartyFormation,
} from './state';
export { tick } from './tick';
export {
  applyTowerResult,
  clearedFloors,
  emptyTowers,
  floorKindAt,
  floorLevel,
  floorsClearedIn,
  floorSummons,
  isTowerUnlocked,
  matchedStageIndex,
  nextFloor,
  parseTowers,
  resolveFloor,
  resolveTower,
  type TowerBattleOutcome,
  type TowerData,
  type TowerFloorData,
  type TowerDropAward,
  type TowerProgress,
  type TowerRulesData,
} from './towers';
